[UPD] UI update complete
ToGatherThem/gatherthem_mobile_app pull request #68
Opened 2022-05-20 12:16 UTC by DjibrilQS

2022-05-20 12:22 UTC, smyllet requested changes
Format de date et overflow

2022-06-02 08:06 UTC, Viincii approved these changes

2022-06-02 08:07 UTC, Viincii approved these changes

2022-06-02 08:08 UTC, YanisBft approved these changes

2022-06-02 08:08 UTC, smyllet approved these changes

2022-06-02 08:08 UTC, merged